name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch: # Allows manual triggering

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Speeku  # Change this to your GitHub organization name
          template: classic
          base: header, activity, community, repositories
