name: Update README

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main, production ]
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          python .github/scripts/update_readme.py
